import * as XLSX from 'xlsx';
import { RDAccountData } from '../types';

export const generateExcelReport = (data: RDAccountData) => {
  const accountData = data as any;

  const transactions = accountData.transactions || [];

  const customerName =
    accountData.customerName || 'Not Specified';

  const accountNumber =
    accountData.accountNumber || 'Not Specified';

  const rdType =
    accountData.rdType || 'Recurring Deposit (RD)';

  const openingDate =
    accountData.openingDate || 'Not Specified';

  const maturityDate =
    accountData.maturityDate || 'Not Specified';

  const period =
    accountData.period || 'Not Specified';

  const interestRate =
    typeof accountData.annualRate === 'number'
      ? `${(accountData.annualRate * 100).toFixed(2)}%`
      : 'Not Specified';

  const totalDeposited =
    Number(accountData.totalDeposited || 0);

  const totalInterest =
    Number(accountData.totalInterest || 0);

  const maturityAmount =
    Number(accountData.maturityAmount || 0);

  // ============================================================
  // SHEET 1 - RD SUMMARY
  // ============================================================

  const summaryData = [
    ['RD CALCULATOR REPORT'],
    ['Recurring Deposit Calculation Statement'],
    [],

    ['CUSTOMER & RD DETAILS'],
    ['Customer Name', customerName],
    ['Account Number', accountNumber],
    ['RD Type', rdType],
    ['Opening Date', openingDate],
    ['Maturity Date', maturityDate],
    ['Period / Tenure', period],
    ['Interest Rate', interestRate],
    ['Number of Transactions', accountData.validTransactionCount || transactions.length],

    [],

    ['FINANCIAL SUMMARY'],
    ['Total Deposited', totalDeposited],
    ['Total Interest', totalInterest],
    ['Maturity Amount', maturityAmount],

    [],

    ['CALCULATION METHODOLOGY'],

    ...(rdType === 'Monthly RD'
      ? [
          [
            '1',
            'Monthly Installment',
            'Total Deposited ÷ Number of Deposits',
          ],
          [
            '2',
            'Progressive Interest',
            'Interest = Installment × Monthly Rate × Months Remaining',
          ],
          [
            '3',
            'Final Maturity',
            'Maturity Amount = Total Deposited + Total Interest',
          ],
        ]
      : [
          [
            '1',
            'Deposit Normalization',
            'Daily RD Amount = Total Deposited ÷ 365',
          ],
          [
            '2',
            'Progressive Interest',
            'Day i Interest = Daily Amount × Annual Rate × (i ÷ 365)',
          ],
          [
            '3',
            'Final Maturity',
            'Maturity Amount = Total Deposited + Total Interest',
          ],
        ]),

    [],

    ['Report Information'],
    ['Generated By', 'RD Calculator'],
    ['Report Type', 'Excel Calculation Report'],
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);

  // Column widths
  summarySheet['!cols'] = [
    { wch: 25 },
    { wch: 28 },
    { wch: 65 },
  ];

  // Merge title rows
  summarySheet['!merges'] = [
    {
      s: { r: 0, c: 0 },
      e: { r: 0, c: 2 },
    },
    {
      s: { r: 1, c: 0 },
      e: { r: 1, c: 2 },
    },
    {
      s: { r: 3, c: 0 },
      e: { r: 3, c: 2 },
    },
    {
      s: { r: 13, c: 0 },
      e: { r: 13, c: 2 },
    },
    {
      s: { r: 18, c: 0 },
      e: { r: 18, c: 2 },
    },
  ];

  // ============================================================
  // SHEET 2 - LEDGER
  // ============================================================

  const ledgerHeader = [
    [
      'Row',
      'Date',
      'Particulars',
      'Debit',
      'Receipt / Credit',
      'Balance',
      'Interest Paid',
    ],
  ];

  const ledgerRows = transactions.map(
    (transaction: any, index: number) => {
      return [
        transaction.rowNum || index + 1,
        transaction.date || '',
        transaction.particulars || '',
        transaction.debit != null
          ? Number(transaction.debit)
          : '',
        transaction.rawReceipt ||
          transaction.payment ||
          '',
        transaction.balance != null
          ? Number(transaction.balance)
          : '',
        transaction.intPaid != null
          ? Number(transaction.intPaid)
          : '',
      ];
    }
  );

  if (ledgerRows.length === 0) {
    ledgerRows.push([
      '',
      '',
      'No transaction records available',
      '',
      '',
      '',
      '',
    ]);
  }

  const ledgerSheet = XLSX.utils.aoa_to_sheet([
    ...ledgerHeader,
    ...ledgerRows,
  ]);

  ledgerSheet['!cols'] = [
    { wch: 8 },
    { wch: 15 },
    { wch: 40 },
    { wch: 15 },
    { wch: 18 },
    { wch: 18 },
    { wch: 18 },
  ];

  // Freeze the header row
  ledgerSheet['!freeze'] = {
    xSplit: 0,
    ySplit: 1,
  };

  // ============================================================
  // SHEET 3 - CALCULATION
  // ============================================================

  const calculationData = [
    ['CALCULATION DETAILS'],
    [],

    ['RD Type', rdType],
    ['Interest Rate', interestRate],
    ['Period', period],

    [],
    ['Total Deposited', totalDeposited],
    ['Total Interest', totalInterest],
    ['Maturity Amount', maturityAmount],

    [],
    ['Valid Transactions', accountData.validTransactionCount || transactions.length],
    ['Tenure Days', accountData.tenureDays || ''],
  ];

  const calculationSheet =
    XLSX.utils.aoa_to_sheet(calculationData);

  calculationSheet['!cols'] = [
    { wch: 30 },
    { wch: 30 },
  ];

  // ============================================================
  // CREATE WORKBOOK
  // ============================================================

  const workbook = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(
    workbook,
    summarySheet,
    'RD Summary'
  );

  XLSX.utils.book_append_sheet(
    workbook,
    ledgerSheet,
    'Ledger'
  );

  XLSX.utils.book_append_sheet(
    workbook,
    calculationSheet,
    'Calculation'
  );

  // ============================================================
  // FILE NAME
  // ============================================================

  const safeCustomerName = customerName
    .replace(/[^a-z0-9]/gi, '_')
    .substring(0, 30);

  const fileName =
    `RD_Report_${safeCustomerName}.xlsx`;

  // ============================================================
  // DOWNLOAD
  // ============================================================

  XLSX.writeFile(workbook, fileName);
};